### ISSUE TITLE
NullPointer if command has no arguments

### ISSUE THREAD

**Issue by creckord** [maybeec/oomph-task-cli#11]
The cliTask throws a NullPointerException if no arguments are specified:

```java
java.lang.NullPointerException
  at com.github.maybeec.oomph.task.cli.core.impl.CommandLineUtilImpl.stringListToLine(CommandLineUtilImpl.java:92)
  at com.github.maybeec.oomph.task.cli.core.impl.CommandLineUtilImpl.execute(CommandLineUtilImpl.java:54)
  at com.github.maybeec.oomph.task.cli.impl.cliTaskImpl.perform(cliTaskImpl.java:307)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededTask(SetupTaskPerformer.java:2869)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3104)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3032)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3013)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2944)
```

This is caused by `cliTask.execute()` calling the CommandLineUtilImpl with `CommandLineUtilImpl.getInstance().execute(directory, command, argument);` which leaves the `argument` List object uninitialized if the task has no arguments set.

**Comment by themetalone** [comment]
I see were the error comes from and will fix that. Interesting is that we also use argument free calls without running into it...

**Comment by themetalone** [comment]
Fix should be deployed to the update site by now
